name: Create and publish app release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: Major/minor/patch?
        type: choice
        required: true
        options:
          - major
          - minor
          - patch
        default: patch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Write keystore file
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          TMP_KEYSTORE_PATH="${RUNNER_TEMP}"/keystore
          mkdir -p "${TMP_KEYSTORE_PATH}"
          echo $ANDROID_KEYSTORE_BASE64 | base64 -di > "${TMP_KEYSTORE_PATH}"/yatoo.jks

      - run: npm ci

      - name: read versions
        id: read-version
        run: |
          echo "version=$(jq -r ".version" package.json)" >> $GITHUB_OUTPUT
          echo "tag=v$(jq -r ".version" package.json)"  >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump-version
        run: echo "version=$(npx --yes semver -i ${{inputs.increment}} ${{steps.read-version.outputs.version}})" >> $GITHUB_OUTPUT

      - name: Update version in package.json
        run: sed -i -r 's/("version":\s*")(.*)"/\1${{steps.bump-version.outputs.version}}"/' package.json

      - name: Updateversion in electron/package.json
        run: sed -i -r 's/("version":\s*")(.*)"/\1${{steps.bump-version.outputs.version}}"/' electron/package.json

      - name: Update version in android/app/build.gradle
        run: sed -i -r 's/versionName\s"([0-9.]+)"/versionName "${{steps.bump-version.outputs.version}}"/' android/app/build.gradle

      - name: Increment android version code
        run: sed -i -r 's/(.*versionCode\s*)([0-9]+)/echo "\1$((\2+1))"/e' android/app/build.gradle

      - name: Fix version in package-lock.json files
        run: npm i && cd electron && npm i

      - name: Commit new version
        run: git commit --all --message "Release ${{steps.bump-version.outputs.version}}"

      - name: Add git tag
        run: git tag --annotate --message "v${{steps.bump-version.outputs.version}}" v${{steps.bump-version.outputs.version}}

      - name: Run production build
        run: npm run build-prod
